// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_i_went_down_the_rapids = "CgkIvKKa9fYQEAIQCg"; // <GPGSID>
        public const string achievement_the_big_imperfect_circle = "CgkIvKKa9fYQEAIQCA"; // <GPGSID>
        public const string achievement_fragmented_life = "CgkIvKKa9fYQEAIQAg"; // <GPGSID>
        public const string achievement_living_vigorously = "CgkIvKKa9fYQEAIQBQ"; // <GPGSID>
        public const string achievement_the_secret_of_the_vault = "CgkIvKKa9fYQEAIQBA"; // <GPGSID>
        public const string achievement_all_power_to_the_people = "CgkIvKKa9fYQEAIQBg"; // <GPGSID>
        public const string achievement_fragmented_power = "CgkIvKKa9fYQEAIQAw"; // <GPGSID>
        public const string achievement_rising_from_the_depths = "CgkIvKKa9fYQEAIQCQ"; // <GPGSID>
        public const string achievement_obtaining_values = "CgkIvKKa9fYQEAIQBw"; // <GPGSID>
        public const string achievement_the_shadow_arrow_wizard = "CgkIvKKa9fYQEAIQCw"; // <GPGSID>
        public const string achievement_squeeze_to_drop_the_last_drop = "CgkIvKKa9fYQEAIQDA"; // <GPGSID>
        public const string achievement_sword_emblem = "CgkIvKKa9fYQEAIQAQ"; // <GPGSID>

}

